---
#
# Installing Filebeat
#

# Install Filebeat 

- name: Install Filebeat with yum
  yum:
   name: filebeat
   update_cache: yes
    
# Starting Filebeat

- name: Starting Filebeat
  service:
   name: filebeat
   state: started
