---
# per http://prefetch.net/blog/index.php/2017/09/08/install-metricbeats-with-ansible-and-the-elastic-yum-repository/
# and https://www.elastic.co/guide/en/beats/metricbeat/current/setup-repositories.html
- name: Add Elasticsearch 6.x repository
  yum_repository:
    name: elastic-6.x
    description: Elastic repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
    enabled: yes
    owner: root
    group: root
    state: present
    mode: 0600
